name: rasa
channels:
- defaults
dependencies:
- attrs=19.1.0=py37_1
- backcall=0.1.0=py37_0
- bleach=3.1.0=py37_0
- ca-certificates=2019.8.28=0
- certifi=2019.9.11=py37_0
- colorama=0.4.1=py37_0
- decorator=4.4.0=py37_1
- defusedxml=0.6.0=py_0
- entrypoints=0.3=py37_0
- ipykernel=5.1.2=py37h39e3cac_0
- ipython=7.8.0=py37h39e3cac_0
- ipython_genutils=0.2.0=py37_0
- jedi=0.15.1=py37_0
- jinja2=2.10.1=py37_0
- jsonschema=3.0.2=py37_0
- jupyter_client=5.3.3=py37_1
- jupyter_core=4.5.0=py_0
- libsodium=1.0.16=h9d3ae62_0
- m2w64-gcc-libgfortran=5.3.0=6
- m2w64-gcc-libs=5.3.0=7
- m2w64-gcc-libs-core=5.3.0=7
- m2w64-gmp=6.1.0=2
- m2w64-libwinpthread-git=5.0.0.4634.697f757=2
- markupsafe=1.1.1=py37he774522_0
- mistune=0.8.4=py37he774522_0
- msys2-conda-epoch=20160418=1
- nb_conda_kernels=2.2.2=py37_0
- nbconvert=5.6.0=py37_1
- nbformat=4.4.0=py37_0
- notebook=6.0.1=py37_0
- openssl=1.1.1d=he774522_2
- pandoc=2.2.3.2=0
- pandocfilters=1.4.2=py37_1
- parso=0.5.1=py_0
- pickleshare=0.7.5=py37_0
- pip=19.2.3=py37_0
- prometheus_client=0.7.1=py_0
- prompt_toolkit=2.0.9=py37_0
- pygments=2.4.2=py_0
- pyrsistent=0.15.4=py37he774522_0
- python=3.7.4=h5263a28_0
- python-dateutil=2.8.0=py37_0
- pywin32=223=py37hfa6e2cd_1
- pywinpty=0.5.5=py37_1000
- pyzmq=18.1.0=py37ha925a31_0
- send2trash=1.5.0=py37_0
- setuptools=41.2.0=py37_0
- six=1.12.0=py37_0
- sqlite=3.30.0=he774522_0
- terminado=0.8.2=py37_0
- testpath=0.4.2=py37_0
- tornado=6.0.3=py37he774522_0
- traitlets=4.3.2=py37_0
- vc=14.1=h0510ff6_4
- vs2015_runtime=14.16.27012=hf0eaf9b_0
- wcwidth=0.1.7=py37_0
- webencodings=0.5.1=py37_1
- wheel=0.33.6=py37_0
- wincertstore=0.2=py37_0
- winpty=0.4.3=4
- zeromq=4.3.1=h33f27b4_3
prefix: C:\Users\YogeshKulkarni\AppData\Local\conda\conda\envs\rasa

