graph_construction_name: "node_emb"
graph_embedding_name: "gat"
decoder_name: "stdrnn"

graph_construction_args:
  graph_construction_share:
    graph_type: 'node_emb'
    root_dir: "../data/jobs"
    topology_subdir: 'NodeEmbGraph'
    thread_number: 4
    port: 9000
    timeout: 15000

  graph_construction_private:
    edge_strategy: 'homogeneous'
    merge_strategy: 'tailhead'
    sequential_link: true
    as_node: false

  node_embedding:
    input_size: 300
    hidden_size: 300
    word_dropout: 0.2
    rnn_dropout: 0.3
    fix_bert_emb: false
    fix_word_emb: false
    embedding_style:
      single_token_item: true
      emb_strategy: "w2v_bilstm"
      num_rnn_layers: 1
      bert_model_name: null
      bert_lower_case: null

    sim_metric_type: 'weighted_cosine'
    num_heads: 1
    top_k_neigh: null
    epsilon_neigh: 0.5
    smoothness_ratio: 0.1
    connectivity_ratio: 0.05
    sparsity_ratio: 0.1

graph_embedding_args:
  graph_embedding_share:
    num_layers: 3
    input_size: 300
    hidden_size: 300
    output_size: 300
    direction_option: "bi_sep"
    feat_drop: 0.2

  graph_embedding_private:
    heads: [2, 2, 1]
    attn_drop: 0.2
    negative_slope: 0.2
    residual: false
    activation: "relu"

decoder_args:
  rnn_decoder_share:
    rnn_type: "lstm"
    input_size: 300
    hidden_size: 512
    rnn_emb_input_size: 300
    use_copy: true
    use_coverage: true
    graph_pooling_strategy: null
    attention_type: "sep_diff_encoder_type"
    fuse_strategy: "concatenate"
    dropout: 0.3

  rnn_decoder_private:
    max_decoder_step: 50
    node_type_num: null
    tgt_emb_as_output_layer: true

other_args:
  seed: 1236
  checkpoint_save_path: 'out/jobs/gat_bi_sep_node_emb_ckpt'
  pretrained_word_emb_name: '6B'
  pretrained_word_emb_url: None
  pretrained_word_emb_cache_dir: '.vector_cache'
  share_vocab: True
  word_emb_size: 300
  beam_size: 4
  batch_size: 24
  learning_rate: 1.e-3
  loss_display_step: 10
  eval_display_number: 10
  lr_start_decay_epoch: 20
  lr_decay_rate: 0.9
  lr_decay_per_epoch: 5
  min_lr: 1.e-3
  val_split_ratio: 0
  use_gpu: 1 # 0 for don't use cuda, 1 for using cuda
  gpu: 0 # gpu id
