name: rasa
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - certifi=2019.9.11=py36_0
  - icc_rt=2019.0.0=h0cc432a_1
  - implicit=0.4.0=py36he350917_0
  - intel-openmp=2019.4=245
  - libblas=3.8.0=13_mkl
  - libcblas=3.8.0=13_mkl
  - liblapack=3.8.0=13_mkl
  - mkl=2019.4=245
  - mkl-service=2.3.0=py36hfa6e2cd_0
  - numpy=1.17.2=py36hc71023c_0
  - pip=19.2.3=py36_0
  - python=3.6.9=h5500b2f_0
  - setuptools=41.2.0=py36_0
  - sqlite=3.30.0=he774522_0
  - tqdm=4.36.1=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wheel=0.33.6=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - pip:
    - absl-py==0.8.0
    - aiofiles==0.4.0
    - aiohttp==3.6.1
    - apscheduler==3.6.1
    - asn1crypto==1.0.1
    - astor==0.8.0
    - async-generator==1.10
    - async-timeout==3.0.1
    - attrs==19.2.0
    - automat==0.7.0
    - boto3==1.9.243
    - botocore==1.12.243
    - bz2file==0.98
    - cachetools==3.1.1
    - cffi==1.12.3
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==0.6.1
    - colorama==0.4.1
    - colorclass==2.2.0
    - coloredlogs==10.0
    - colorhash==1.0.2
    - configargparse==0.14.0
    - constantly==15.1.0
    - cryptography==2.7
    - cycler==0.10.0
    - cymem==2.0.2
    - cytoolz==0.9.0.1
    - decorator==4.4.0
    - dill==0.2.9
    - dnspython==1.16.0
    - docopt==0.6.2
    - docutils==0.15.2
    - dopamine-rl==2.0.5
    - en-core-web-md==2.0.0
    - en-core-web-sm==2.0.0
    - fbmessenger==6.0.0
    - flask==1.1.1
    - flask-cors==3.0.8
    - future==0.17.1
    - gast==0.2.2
    - gevent==1.4.0
    - gin-config==0.2.1
    - google-api-python-client==1.7.11
    - google-auth==1.6.3
    - google-auth-httplib2==0.0.3
    - google-pasta==0.1.7
    - googleapis-common-protos==1.6.0
    - greenlet==0.4.15
    - grpcio==1.24.1
    - gunicorn==19.9.0
    - gym==0.14.0
    - h5py==2.10.0
    - httplib2==0.14.0
    - httptools==0.0.13
    - humanfriendly==4.18
    - hyperlink==19.0.0
    - idna==2.8
    - idna-ssl==1.1.0
    - incremental==17.5.0
    - itsdangerous==1.1.0
    - jinja2==2.10.3
    - jmespath==0.9.4
    - jsonpickle==1.2
    - jsonschema==2.6.0
    - kafka-python==1.4.7
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kfac==0.2.0
    - kiwisolver==1.1.0
    - klein==17.10.0
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.1
    - mattermostwrapper==2.1
    - mesh-tensorflow==0.0.5
    - mock==3.0.5
    - mpmath==1.1.0
    - msgpack==0.5.6
    - msgpack-numpy==0.4.3.2
    - multidict==4.5.2
    - murmurhash==1.0.2
    - networkx==2.3
    - oauth2client==4.1.3
    - opencv-python==4.1.1.26
    - packaging==19.2
    - pika==1.0.1
    - pillow==6.2.0
    - plac==0.9.6
    - preshed==2.0.1
    - promise==2.2.1
    - prompt-toolkit==2.0.10
    - protobuf==3.10.0
    - psutil==5.6.3
    - pyasn1==0.4.7
    - pyasn1-modules==0.2.6
    - pycparser==2.19
    - pydot==1.4.1
    - pyglet==1.3.2
    - pyhamcrest==1.9.0
    - pyjwt==1.7.1
    - pykwalify==1.7.0
    - pymongo==3.9.0
    - pyparsing==2.4.2
    - pypng==0.0.20
    - pyreadline==2.1
    - pysocks==1.7.1
    - python-crfsuite==0.9.6
    - python-dateutil==2.8.0
    - python-engineio==3.9.3
    - python-socketio==4.3.1
    - python-telegram-bot==11.1.0
    - pytz==2019.2
    - pyyaml==5.1.2
    - questionary==1.3.0
    - rasa==1.3.7
    - rasa-sdk==1.3.3
    - redis==3.3.8
    - regex==2018.01.10
    - requests==2.22.0
    - requests-toolbelt==0.9.1
    - rocketchat-api==0.6.34
    - rsa==4.0
    - ruamel-yaml==0.15.100
    - s3transfer==0.2.1
    - sanic==19.3.1
    - sanic-cors==0.9.9.post3
    - sanic-jwt==1.3.2
    - sanic-plugins-framework==0.8.2
    - scikit-learn==0.20.4
    - scipy==1.3.1
    - simplejson==3.16.0
    - six==1.12.0
    - sklearn-crfsuite==0.3.6
    - slackclient==1.3.2
    - spacy==2.0.18
    - sqlalchemy==1.3.9
    - sympy==1.4
    - tabulate==0.8.5
    - tensor2tensor==1.14.1
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-datasets==1.2.0
    - tensorflow-estimator==1.14.0
    - tensorflow-gan==1.0.0.dev0
    - tensorflow-metadata==0.14.0
    - tensorflow-probability==0.7.0
    - termcolor==1.1.0
    - terminaltables==3.1.0
    - thinc==6.12.1
    - toolz==0.10.0
    - twilio==6.31.1
    - twisted==19.7.0
    - typing==3.7.4.1
    - typing-extensions==3.7.4
    - tzlocal==2.0.0
    - ujson==1.35
    - uritemplate==3.0.0
    - urllib3==1.25.6
    - wcwidth==0.1.7
    - webexteamssdk==1.2
    - websocket-client==0.54.0
    - websockets==6.0
    - werkzeug==0.16.0
    - wrapt==1.11.2
    - yarl==1.3.0
    - zope-interface==4.6.0
prefix: C:\Users\yogesh.kulkarni\AppData\Local\Continuum\anaconda3\envs\rasa

