intents:
- ticket
- inform
- affirmation
- deny

entities:
- location 
- date

slots:
   from:
            type: text
   to:
            type: text
   date:
            type: text

actions:
- utter_boarding
- utter_destination
- utter_date
- utter_confirm
- utter_check_another_one
- utter_thanks
- utter_unclear
- action_save_origin
- action_save_destination
- action_save_date
- action_get_flight
- action_slot_reset
templates:
  
  utter_boarding:
  - text: "We'll help you find the latest flight schedule. First, please provide your origin airport code?"
  
  utter_destination:
  - text: "And the destination airport code?"
  
  utter_date:
  - text: "What is the date for your travel(in dd-mm-yyyy)?"
  
  utter_confirm:
  - text: "I will be making inquiry for flight from {from} to {to} on {date}. Is that correct?"
  
  utter_check_another_one:
  - text: "Do you want to make another inquiry?"
  
  utter_thanks:
  - text: "Thanks for contacting us. Have a good day!"
  
  utter_unclear:
  - text: "I am not sure what you are aiming for.Kindly try it again"
  
